---
swagger: "2.0"
info:
  description: "A simple service to get timestamp info as an example of using swagger\
    \ -2.0 specification and codegen"
  version: "0.0.1"
  title: "Timestampinfo"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Cloudmesh REST Service"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /timestamp:
    get:
      description: "Returns timestamp information of the file"
      operationId: "timestamp_get"
      produces:
      - "application/json"
      parameters:
      - name: "path"
        in: "query"
        description: "Path to file"
        required: true
        type: "string"
      responses:
        200:
          description: "timestamp info"
          schema:
            $ref: "#/definitions/TIMESTAMP"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  TIMESTAMP:
    type: "object"
    required:
    - "Timestamp"
    properties:
      Timestamp:
        type: "string"
    example:
      Timestamp: "Timestamp"
