swagger: "2.0"
info:
  version: "0.0.1"
  title: "Timestampinfo"
  description: "A simple service to get timestamp info as an example of using swagger -2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"

  contact:
    name: "Cloudmesh REST Service"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /timestamp:
    get:
      description: "Returns timestamp information of the file"
      produces:
        - "application/json"
      parameters:  
        - in: "query"
          name: "path"
          allowReserved: "true"
          required: "true"
          description: "Path to file"
          type: "string" 
          
               
      responses:

        "200":
          description: "timestamp info"
          schema:
            $ref: "#/definitions/TIMESTAMP"


definitions:
  TIMESTAMP:
    type: "object"
    required:
      - "Timestamp"
    properties:
      Timestamp:
        type: "string"
    
      



 
